language: generic
sudo: required
services: -docker

before_install:
  - docker build -t constaned/docker-test -f Dockerfile.dev .

script: CI=true
  - docker run -e CI=true constaned/docker-test npm run test -- --coverage
